# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt ./
RUN pip install --no-cache-dir --ignore-installed -r requirements.txt

# Copy application code
COPY . .

# Expose nothing; stdio

# Default command
ENTRYPOINT ["python", "main.py"]
